apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-operators
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    path: servicemesh/operators
    repoURL: https://github.com/cziesman/rhte-cluster-gitops
    targetRevision: HEAD
  syncPolicy:
    automated: {}
